version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs:latest
    container_name: nodejs
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/mydb
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodata: